name: alterego
description: Deepfake creator client.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view:
    git:
      url: https://github.com/BertrandBev/flutter_staggered_grid_view.git
  auto_localized: ^0.7.0
  camera: ^0.5.8+11
  dio: ^3.0.10
  dotted_border: ^1.0.6
  equatable: ^1.2.5
  firebase_messaging: ^7.0.3
  flutter_bloc: ^6.0.0
  flutter_secure_storage: ^3.3.5
  flutter_settings_screens: ^0.2.1
  flutter_signin_button: ^1.1.0
  get: ^3.22.2
  image: ^2.1.19
  image_picker: ^0.6.7+14
  intl: ^0.16.1
  meta: ^1.2.2
  path: ^1.7.0
  path_provider: ^1.6.14
  pull_to_refresh: ^1.6.2
  video_player: ^0.11.0
  wave: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_localized_generator: ^0.7.1
  build_runner: ^1.10.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
